# Increase the heap size for the Gradle daemon
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError

# Enable parallel builds
org.gradle.parallel=true

# Enable caching between builds
org.gradle.caching=true

# Enable configuration caching
org.gradle.configuration-cache=true

# AndroidX properties
android.useAndroidX=true
android.nonTransitiveRClass=true
